### ISSUE TITLE
How to add api key

### ISSUE THREAD

**Issue by Roboxkin** [systemcaller/CDNRECON#3]
How to add api key? how to write in terminal?
F:\CloudFail>main.py --write ckk.ai --shodan apikey
usage: main.py [-h] [-c CONFIG] [--write] domain
main.py: error: unrecognized arguments: --shodan apikey

F:\CloudFail>main.py --write ckk.ai -c shodan=apikey
Traceback (most recent call last):
  File "F:\CloudFail\main.py", line 62, in <module>
    for LINE in open(ARGS.config, 'r'):
                ^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'shodan=apikey'

F:\CloudFail>main.py --write ckk.ai -config shodan=apikey
usage: main.py [-h] [-c CONFIG] [--write] domain
main.py: error: unrecognized arguments: shodan=apikey

**Comment by R00tendo** [comment]
The -c flag is used to specify a FILE with the api keys like this:
```bash
$cat config_file
shodan=jfjirj34j23lj4k23j4jk23j4
$python3 main.py --write ckk.ai -c config_file
Some output
```

**Comment by systemcaller** [comment]
Make a config.txt file that looks like this;
shodan=key-here

Then run the script with the -c flag like so: 
`python3 main.py example.com -c config.txt`

**Comment by Roboxkin** [comment]
> Make a config.txt file that looks like this; shodan=key-here
> 
> Then run the script with the -c flag like so: `python3 main.py example.com -c config.txt`

Thank you very much for your help! It works well.
